package org.apache.spark.daslab.sql.engine.plans.logical

import org.apache.spark.daslab.sql.engine.expressions.Attribute


/**
 * A general hint for the child that is not yet resolved. This node is generated by the parser and
 * should be removed This node will be eliminated post analysis.
 * @param name the name of the hint
 * @param parameters the parameters of the hint
 * @param child the [[LogicalPlan]] on which this hint applies
 */
case class UnresolvedHint(name: String, parameters: Seq[Any], child: LogicalPlan)
  extends UnaryNode {

  override lazy val resolved: Boolean = false
  override def output: Seq[Attribute] = child.output
}

/**
 * A resolved hint node. The analyzer should convert all [[UnresolvedHint]] into [[ResolvedHint]].
 */
case class ResolvedHint(child: LogicalPlan, hints: HintInfo = HintInfo())
  extends UnaryNode {

  override def output: Seq[Attribute] = child.output

  override def doCanonicalize(): LogicalPlan = child.canonicalized
}


case class HintInfo(broadcast: Boolean = false) {

  /** Must be called when computing stats for a join operator to reset hints. */
  def resetForJoin(): HintInfo = copy(broadcast = false)

  override def toString: String = {
    val hints = scala.collection.mutable.ArrayBuffer.empty[String]
    if (broadcast) {
      hints += "broadcast"
    }

    if (hints.isEmpty) "none" else hints.mkString("(", ", ", ")")
  }
}
